# Development — lowest cost, single replica, no HPA/PDB noise
environment:
  name: development
  tier: non-production

replicaCount: 1
env: dev
host: dev.interview.com

image:
  repository: interviewresgistry.azurecr.io/interview-app-image
  tag: ""

service:
  type: ClusterIP
  port: 80

containerPort: 8083

ingress:
  enabled: true
  className: nginx
  extraAnnotations: {}

hpa:
  enabled: false
  min: 1
  max: 2

pdb:
  enabled: false

podAntiAffinity:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
