replicaCount: 2
env: staging

# 👇 NEW
host: staging.interview.com

image:
  repository: interviewresgistry.azurecr.io/interview-app-image
  tag: ""

service:
  type: ClusterIP
  port: 80

hpa:
  enabled: true
  min: 2
  max: 3

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"