replicaCount: 3
env: prod

# 👇 different host
host: prod.interview.com

image:
  repository: interviewresgistry.azurecr.io/interview-app-image
  tag: ""

service:
  type: ClusterIP
  port: 80

hpa:
  min: 3
  max: 6

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"