replicaCount: 3
env: dev
host: interview-prod.local

image:
  repository: interviewresgistry.azurecr.io/interview-app-image
  tag: ""

service:
  type: ClusterIP
  port: 80

hpa:
  enabled: true
  min: 3
  max: 6

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"